### ISSUE TITLE
Implement a retry count for failed message handles

### ISSUE THREAD

**Issue by MrCreosote** [kbase/index_runner#126]
In https://github.com/kbase/index_runner_deluxe/blob/develop/src/index_runner/main.py#L121-L130, it seems as though if `_handle_msg` throws an exception, the kafka client will not commit the offset, and therefore the same message will be processed again, presumably throwing the same exception again.

**Comment by jayrbolton** [comment]
Yeah, good point. In practice this was done because many of our dependent services are unreliable, and the errors are temporary, and this was a quick solution to get retires. But we really need to implement a retry count.

**Comment by jayrbolton** [comment]
If you don't mind, I will rename this issue to "Implement a retry count for failed message handles"
