### ISSUE TITLE
Support deploying multiple indexers specialized for certain indexes

### ISSUE THREAD

**Issue by scanon** [kbase/index_runner#142]
Some indexes will be more time sensitive than others.  We would like to be able to deploy indexers that are specialized.

Some examples....

* narrative indexers - These may need to run very fast to support the dashboard
* basic object indexers - These can run fast and may eventually be used in both the UI search and narrative search
* AMA and genome indexers - (Really anything with features) These can take a long time.  They do need to run in a predictable period because viewers may depend on them, but they can't block some of the other things that could run more quickly.
* sample indexers - These may be in this code base but they need to subscribe to a different Kafka stream.

I'm not sure of the implementation.  We could have a special launcher for each or we could manage it all with a config for each.  The later could be more flexible but we need to think through all the scenarios.  

We also need to consider if one indexer is handling say the main object index (e.g. an AMA), and if there is a special feature indexer, it needs to be designed to not just check if the top level index record exists.  Basically the feature indexers need to have an independent way to tell if an object has been indexed.

With all of these we also need to consider how reindex events will be handled and what indexers would get poked.

**Comment by jayrbolton** [comment]
:+1:

**Comment by jayrbolton** [comment]
Here is what we currently have (all env vars)
* `SKIP_INDICES` is a comma-delimited list of index names to blacklist. The document for the index will still get processed and created, just not saved to ES
* `ALLOW_INDICES` is a comma-delimited list of indexes to whitelist. No other indexes will get saved. Same as above, the index document will still get processed and created, but not saved to elasticsearch.
* `SKIP_RELENG` turns off any importing to arangodb. This prevents any Arango documents getting generated or processed at all.
* `SKIP_FEATURES` turns off any genome feature indexing in both RE and Elasticsearch, and also prevents the features from getting processed and generated

We could add a `TYPE_WHITELIST` option -- list of workspace types to index, ignore everything else. This option could go against the object type given in the workspace event and prevent anything from happening unless the object type from the event is in the list.

For the sample stream, we could have something like:
* `TOPIC_HANDLERS` mapping of topic name to handler name. In the code, we'd keep a mapping from string name to handler module (Workspace-to-ES, Relation Engine, Samples). So you could specify that you want to save workspace objects to Elasticsearch from topic A, and you want to save Sample objects to wherever from topic B

**Comment by jayrbolton** [comment]
SKIP_TYPES and ALLOW_TYPES was implemented

Remaining thing to do is the TOPIC_HANDLERS option described above (or something similar)

**Comment by scanon** [comment]
Good enough.
