### ISSUE TITLE
Update the narrative index when narrative permissions are changed

### ISSUE THREAD

**Issue by jayrbolton** [kbase/index_runner#169]
We may have to listen to another event like WORKSPACE_STATE_CHANGE, because changing narrative perms only does not trigger a narrative save.

**Comment by scanon** [comment]
Issue #168 may be able to handled with the same change.  Maybe just always reindex if anything happens in a workspace assuming it is fast enough.

**Comment by jayrbolton** [comment]
An event with evtype "SET_GLOBAL_PERMISSION" gets published when you change narrative public/private settings in the "Change Share Settings" modal. Here's an example:

```json
{"wsid":53705,"ver":null,"perm":null,"evtype":"SET_GLOBAL_PERMISSION","objid":null,"time":1600303641421,"objtype":null,"permusers":[],"user":"jayrbolton"}
```

We already have a handler for this event, and we have a function in `es_indexer.py` called `set_perms` that handles this, which in turn calls a function `is_workspace_public` in a utils module, which fetches the workspace info and pulls the permissions from there. 

First I'll need to verify that this is actually not working as intended, and if not, trace what's happening.

**Comment by jayrbolton** [comment]
I just tested this manually in CI, and found that the event is received, handled correctly, and the ES doc "is_public" field gets updated within about 25 seconds on CI

**Comment by jayrbolton** [comment]
Also just confirmed that all objects within the narrative get their 'is_public' field toggled correctly on permission change

**Comment by jayrbolton** [comment]
I think the last thing to try and confirm is this behavior:

1. search for a public narrative and get results
1. make narrative private
1. search for same narrative (without result), and we should not get results

**Comment by jayrbolton** [comment]
I've been testing CI a lot, swapping permissions for workspace 53705, and each time i see the correct behavior. When the narrative goes private, the event is handled, and search results for that workspace ID are empty (without auth). With auth, I see results. When I change the narrative to be public, the event is handled, and the results show up for non-authenticated requests. Closing
