### ISSUE TITLE
Signal handler isn't quite right

### ISSUE THREAD

**Issue by scanon** [kbase/index_runner#179]
Seeing this error when I update/restart indexers....

00 2020-10-28T17:34:19.818326339Z Error in atexit._run_exitfuncs:

00 2020-10-28T17:34:19.818562641Z TypeError: <lambda>() missing 2 required positional arguments: 'signum' and 'stack_frame'
###

**Comment by jayrbolton** [comment]
I looked at this before but didn't figure it out. Gavin actually set this line:

```py
    atexit.register(lambda signum, stack_frame: kafka.close_consumer(consumer))
```

Which looks correct to me and has the 2 arguments there

**Comment by jayrbolton** [comment]
Checked the docs and seeing that the function for atexit.register takes no args, while the signal handlers take those two args. Fix pending
