### ISSUE TITLE
Config has multiple indexes in aliases

### ISSUE THREAD

**Issue by scanon** [kbase/index_runner#181]
Several of the aliases include both _1 and _2 variants.  This leads to duplicate results.  I think we should drop all the duplicates.  In the future, we will have to go through a roll out process for any updates.  e.g. add the new version, index everything, then do an update to switch to the new one.

**Comment by jayrbolton** [comment]
Which aliases, the type-specific ones like `genome`? default_search has latest indexes only

**Comment by scanon** [comment]
This has been cleaned up.
