### ISSUE TITLE
Add a config option for events to quietly ignore

### ISSUE THREAD

**Issue by scanon** [kbase/index_runner#193]
Right now some events generate a back trace.  It would be good if there was a config to say what to ignore.

**Comment by jayrbolton** [comment]
I made an update to not throw an error on an unrecognized event, now it just logs a one-line warning. Does this work for what you're talking about? Update is in image tag 1.9.17.

**Comment by scanon** [comment]
That sounds good.

**Comment by jayrbolton** [comment]
:+1:

**Comment by jayrbolton** [comment]
PR #199
